### ISSUE TITLE
[Bug Report]: Conditional rendering "showBegin/showEnd" is adding newlines to document

### ISSUE THREAD

**Issue by exzizt** [carboneio/carbone#121]
I am using the showBegin/showEnd to conditionally render sections but it is adding a newline when it shouldn't be:
![image](https://user-images.githubusercontent.com/17113094/114943735-4f6fa100-9dfb-11eb-9743-51637eeaad49.png)
You can see the section highlighted in green is not being rendered as intended but it seems to be adding a new line to the document before the "Blasting" section which doesn't look good.

Edit:
And it looks worse the more sections that are conditionally removed:
![image](https://user-images.githubusercontent.com/17113094/114944997-6a431500-9dfd-11eb-982b-f34efbb74ecc.png)

How to fix this issue?

**Comment by exzizt** [comment]
To better illustrate the issue using an example from the docs... There would actually be two newlines entered where each hideBegin/hideEnd was:
![image](https://user-images.githubusercontent.com/17113094/115061315-e2f9ae00-9e9d-11eb-891b-6396e33a4803.png)
Is there any push to fix this?

**Comment by dgrelaud** [comment]
Hello, 

Thank you for using Carbone 🙏

Please, can your share your "real" template (without confidential information) to see what happens exactly and how we can solve your issue?

You are right, the example in the documentation is wrong. 
It should be written like that to remove whitespaces and new lines:

```
Banana{d.toBuy:ifEQ(true):hideBegin}
Apple
Pineapple
{d.toBuy:hideEnd}grapes
```

We will update the website soon.

**Comment by atish-kumar-by** [comment]
https://github.com/carboneio/carbone/issues/130#issuecomment-872304141

i have pasted my data, with template. facing similar issue, newline is getting added if value is empty

**Comment by steevepay** [comment]
From your screenshot, the "created" newline is corresponding to the newline at the end of the end marker `{d.edited_fields.exploration_access.reclamation_cost:showEnd}\n`. I would move the `showEnd` marker at the beginning of the next line to wrap the newline in the condition, such as:
![Screenshot 2021-07-05 at 14 56 52](https://user-images.githubusercontent.com/16964532/124475246-c89ae680-dda1-11eb-9d22-308cac6dd860.png)

The documentation has been updated: 
- showBegin/showEnd: https://carbone.io/documentation.html#showbegin-showend-
- hideBegin/hideEnd: https://carbone.io/documentation.html#hidebegin-hideend-
 
I close the issue, feel free to reopen if you got further questions.
