### ISSUE TITLE
[Bug Report]: Images placeholder not filled (grey background) (with workaround)

### ISSUE THREAD

**Issue by Aarbel** [carboneio/carbone#126]
# **Environment**
Plan: Startup
Other: Word 16.49

# To reproduce
1- I Import a blue jpeg square image
2- I crop this image with shape (Square with round corners)
3- I add a Alt text to this image

My template:
![image](https://user-images.githubusercontent.com/25119847/120441949-68b9b600-c385-11eb-8b4a-63175664d6db.png)

# **Expected Behaviour**
![image](https://user-images.githubusercontent.com/25119847/120441977-6f482d80-c385-11eb-9e71-f4a8549d3235.png)

# **Actual Behaviour**
![image](https://user-images.githubusercontent.com/25119847/120443988-7b34ef00-c387-11eb-8ffa-c06398e67dc6.png)

# **Workaround**
Adding a transparent png image of 1x1 in the template solves the problem, all the images placeholders are well filled. Looks like Carbon needs a least one "regular image" to fill all the images placeholders. (weird i know, but it can maybe help you to find the origin of the bug)

**Comment by steevepay** [comment]
Hello @Aarbel,

The dynamic image replacement is only available on Carbone Enterprise Edition through Carbone Render API or Carbone Studio. The issue already exists on our board, and we will notify you when we got further information about this behavior.

I close the issue, it does not concern CarboneJS on Github.
