### ISSUE TITLE
[Bug Report]: Un-predictable template errors when adding formulas and spaces

### ISSUE THREAD

**Issue by Aarbel** [carboneio/carbone#127]
**Environment**
Other: Word 16.49

**Actual Behaviour**
When adding formulas in a docx template, for example:
```
{d.documents[i].lastDocument:ifNEM:hideBegin}
…
{d.documents[i].lastDocument:ifNEM:hideEnd}
```

I often get errors, which are solved adding a space or un-breakable space inside or after / before the formula or elsewhere in the document (yes i know, that's really random).

Looks like the compilation isn't stable if some characters chain are not "standard".

**Comment by steevepay** [comment]
Hello @Aarbel,

Errors are occurring when the template design is not following the Carbone language specification. When creating a template, check out this Style Guide page, it will prevent you to create a corrupted report:
https://help.carbone.io/en-us/article/style-guide-to-design-a-report-z8lv57/

If you didn't succeed to fix the issue after reading this checklist, join a JSON data-set and a template to replicate the issue. Please, isolate the issue with the **minimum of elements**, it will be easier for debugging. Feel free to reopen the issue with an example.
