### ISSUE TITLE
[Feature Request]: Substitutions do not seem to work in conditional statements

### ISSUE THREAD

**Issue by arcshiftsolutions** [carboneio/carbone#129]
**Problem to solve**
When trying to compare two elements using conditionals, the value be compared to isn't substituted. 

**Proposed solution**
Add logic to allow for the substitution. 

**Describe alternatives you've considered**
I've tried several solutions; our use-case is that we have two lines of text on top of each other which are the same, except when there's a difference, which we want to highlight. For example:
```
{d.diffList[i].school.surname:ifEQ(d.diffList[i].min.surname):showBegin}
{d.diffList[i].min.surname}
{d.diffList[i].school.surname:showEnd}
```

We've also tried using the `show` & `elseShow` functionality, but it doesn't seem to do substitutions either.

**Comment by arcshiftsolutions** [comment]
More context:

```
{d.diffList[i]. school.surname}
{d.diffList[i].school.surname:ifEqual(.min.surname,**.min.surname**)}
```

^^ This doesn't work because it doesn't seem to pick up styling changes on the value. i.e. I've bolded `.min.surname` above but it doesn't take when I run it through.

**Comment by steevepay** [comment]
Hello @arcshiftsolutions,
Thank you for using Carbone!
Can you share the corresponding JSON dataset without confidential information?

**Comment by steevepay** [comment]
Did you try the following expression? it should work fine
```
{d.diffList[i].school.surname:ifEQ(.min.surname):showBegin}
{d.diffList[i].min.surname}
{d.diffList[i].school.surname:showEnd}
```
Carbone does not support arrays inside formatters, such as `ifEQ(d.diffList[i].min.surname)`

**Comment by steevepay** [comment]
Or an alternative solution:
```
{d.diffList[i].school.surname:ifEQ(.min.surname):show(.min.surname):elseShow('')}
```

**Comment by arcshiftsolutions** [comment]
Hi @steevepay - thanks for getting back to me.

I tried your recommendation with the following which did not work:

```
{d.diffList[i].school.surname:ifEQ(.min.surname):showBegin}
{d.diffList[i]. min.surname}
{d.diffList[i].school.surname:showEnd}
```

...but the following does work (note the `isEqual`):

```
{d.diffList[i].school.surname:ifEqual(.min.surname):showBegin}
{d.diffList[i]. min.surname}
{d.diffList[i].school.surname:showEnd}
```

Unfortunately this doesn't get me to where we need; long story short we want to **bold** the value when there's a difference. I can't get there with just `isEqual` I can't find any docs on `isNotEqual`. 

Here's our sample payload; I change the surname value to check one way or the other:

```
"diffList": [
  { 
    "school":
    {
      "pen":"123456789",
      "surname":"Jacobson",
      "givenName":"Wilfredo",
      "legalMiddleNames":"",
      "birthDate":"1999/11/05",
      "gender":"M","schoolID":
      "10200009","usualName":
      "Mann, Clement",
      "reason":null
    },
    "min":
    {
      "pen":"123456789",
      "surname":"Jacobson",
      "givenName":"WILFREDO",
      "legalMiddleNames":"",
      "birthDate":"1999/11/05",
      "gender":"M",
      "schoolID":"10200009",
      "usualName":"MANN, CLEMENT",
      "reason":null
    }
  }
]
```

**Comment by arcshiftsolutions** [comment]
I've confirmed that we're using Carbone version 3.1.0.

**Comment by arcshiftsolutions** [comment]
At this point I can't get `ifEQ` to work at all in either of these two ways:

```
{d.diffList[i].school.surname:ifEQ(.min.surname):show(.min.surname):elseShow('Test')}
```

```
{d.diffList[i].school.surname:ifEQ(.min.surname):showBegin}
{d.diffList[i].min.surname}
{d.diffList[i].school.surname:showEnd}
```

The only way I can get a condition to pass is using `ifEqual`.

**Comment by steevepay** [comment]
Sorry for the late reply, based on your JSON dataset I changed the expression into:
```
{d.diffList[i]}
{d.diffList[i].school.surname:ifEQ(..min.surname):showBegin}
{d.diffList[i].min.surname}
{d.diffList[i].school.surname:showEnd}
{d.diffList[i+1]}
```
With 2 dots it works, let me explain why:  If a single dot is used, the `ifEQ` searchs attributes on the `school` object. If we add two dots, we move into the parent scope `diffList`, then we can access to the `min` object and `surname` string.
Also, this expression works with 2 dots:
```
{d.diffList[i].school.surname:ifEQ(..min.surname):show(..min.surname):elseShow('Test')}
```
Here is the documentation of dynamic parameters: https://carbone.io/documentation.html#dynamic-parameters

The `ifEqual` formatter cannot be used with `showBegin/showEnd` and the result you got was not what you expected.
To print a value with `ifEqual`, a second argument has to be passed, such as: `{d.diffList[i].school.surname:ifEqual(..min.surname, 'value to print if it is positive')}`.
But when the expression is false, it returns the value of `.school.surname`. To print a specific value when it's false, you have to chain a `:show` formatter, such as:
```
{d.diffList[i]}
{d.diffList[i].school.surname:ifEqual(..min.surname, 'This is true!'):show('False')}
{d.diffList[i+1]}
```
I recommend you to use only the "ifEQ" formatter, it's easier to understand and smaller.
Reach me if you got further questions ;)
