### ISSUE TITLE
[Feature Request]:  Ability to generate PDF/A compliant files

### ISSUE THREAD

**Issue by CrossPT** [carboneio/carbone#131]
**Problem to solve**
When converting to PDF, allow to pass a parameter to generate PDF/A file.

**Proposed solution**
When adding the convertTo: 'pdf' parameter, add optional parameters to generate the PDF/A file
`{
    convertTo; 'pdf',
    pdfVersion: 1 (Default this to 0, which is a normal PDF file)
}`

**Describe alternatives you've considered**
LibreOffice already allows this to happen when converting a file to a PDF file. You can also generate this via the following command. (note the Export:SelectPdfVersion=1)
soffice --headless --convert-to pdf:"writer_pdf_Export:SelectPdfVersion=1" --outdir outdir input.pdf
Options for selectPdfVersion:
Specifies the version of PDF to emit.
Possible values:

0 = PDF 1.4 (default selection).
1 = PDF/A-1 (ISO 19005-1:2005)
https://wiki.openoffice.org/wiki/API/Tutorials/PDF_export

**Comment by CrossPT** [comment]
Seems that using formatOptions does not seem to work.
`let options = {
  convertTo: {
    formatName    : 'pdf',
    formatOptions : {
      SelectPdfVersion: 1
    }
  }
}`

**Comment by steevepay** [comment]
Hello @CrossPT,
PDF export options are only available on Carbone Render API (Enterprise Edition), but not on Github.
You can request the API and it will work: https://carbone.io/api-reference.html#pdf-export-filter-options

**Comment by omni-htg** [comment]
Hello there, @steevepay !
Mind if I ask:
How were you guys able to introduce the "PDFUACompliance" option to the PDF conversion?
I've been trying to make it work with unoconv to no avail, and when looking into the converter.py source, I'm not able to pinpoint it.
Much appreciated! :)
