### ISSUE TITLE
Display the number

### ISSUE THREAD

**Issue by youthtech-228** [carboneio/carbone#132]
Hi, I face a problem and wanna get a immediate help.
I want to do like this.
"123456.765" => "123,456.77"
How to do this?
Thanks.

**Comment by steevepay** [comment]
Hello @youthtech-228,
You have to use the formatter `formatN` to format a Number according to a locale, here is the documentation: https://carbone.io/documentation.html#formatn-precision-
Quick example, if I use the locale `en-us` on my rendering option, such as: `options = { "lang": "en-us" }`
and we assume we got the following JSON dataset:
```
{
  "value": 123456.765
}
```
On the template, I would write the following expression:
```
{d.value:formatN}
```
Then it should print `123,456.77`.
Let me know how it goes.

**Comment by youthtech-228** [comment]
no, it is not working.

**Comment by steevepay** [comment]
You are probably using the wrong locale, here is the list of all locales: 
https://github.com/carboneio/carbone/blob/bbd7b4e2635db582996ffdc6a12fbc918b2610b0/formatters/_locale.js#L22

If it is still not working, can you share a template, a JSON sample, and your code calling the function `carbone.render`?

**Comment by youthtech-228** [comment]
I call he function carbone.render. I wanna know where the options value should be placed.

**Comment by steevepay** [comment]
You have to pass the options object as a third argument. It is explained on the API reference:
https://carbone.io/api-reference.html#carbone-render
Here is an example:
```
const fs = require('fs');
const carbone = require('carbone');
const FILE_INPUT = './template.docx';
const DATA = {
 "firstname": "John"
}
const OPTIONS = {
  "lang": "en-us" // could be "fr-fr", or something else
}

carbone.render(FILE_INPUT, DATA, OPTIONS, (err, result) => {
  if (err) {
    return console.log(err);
  }
  fs.writeFileSync("report.docx", result);
});
```

**Comment by youthtech-228** [comment]
yes. I did it with a little different way.  Anyway works well.
Thanks for your help.
