### ISSUE TITLE
Problems with loops and repetitions in  NW.js

### ISSUE THREAD

**Issue by Daniil-Sokolov** [carboneio/carbone#134]
**Environment**
Carbone Version: [e.g. Carbone 1.2.1]
Node Version: [e.g. Node 16.4.0]
Browsers: [e.g. Chromium 91.0.4472.114]
Desktop OS: [e.g. Kubuntu 20.04]

Hello
I am using carbone module in my personal NW.js project and it works
But i have one problem
don`t works loops and repetitions

If i use carbone just like script, in js file and call this from terminal, loops and repetitions are working

but if i use carbone from NW.js all is working, but loops and repetitions not works
and i don`t see errors in console.log output

**Comment by steevepay** [comment]
Hello @Daniil-Sokolov,
Can you share an example with the minimum of elements to replicate the issue?
