### ISSUE TITLE
[Question]: How can I increase the value of parameter converterFactoryTimeout

### ISSUE THREAD

**Issue by gabrielburich** [carboneio/carbone#142]
I am having this problem when generating reports with lots of data. I would like to know if it is possible to increment the value of the parameter converterFactoryTimeout

```
Error: Document conversion timeout reached (60000 ms)
    at Timeout.<anonymous> (/opt/report_service/node_modules/carbone/lib/converter.js:454:19)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

**Comment by loneil** [comment]
There is a `converterFactoryTimeout` parameter that can be supplied to Carbone in the options object. I've had this work for me on an application that uses Carbone in the past.

Options: https://github.com/carboneio/carbone/blob/0749dc1b7cbc59d098efbd664f2da23ad32f16a7/lib/index.js

**Comment by gabrielburich** [comment]
@loneil thank you
