### ISSUE TITLE
[Feature Request]: Print index of an array

### ISSUE THREAD

**Issue by antipopp** [carboneio/carbone#158]
**Problem to solve**
I'm trying to generate a report from a form. The report should be divided in numbered paragraphs and just printing the index would be helpful, along with the paragraph name.

**Proposed solution**
Maybe something like `{d.items[i]:arrayIndex} {d.items[i].title}` or some other reserved word

**Describe alternatives you've considered**
Adding the index to the object and calculating it at runtime, like  `{d.items[i].pNumber} {d.items[i].title}`

**Comment by antipopp** [comment]
I found a way by using Word numbered list. You basically set up the first item of the list and then loop the array.

**Comment by agustaf9** [comment]
This feature would be useful to me as well. I am using excel, so I cannot create a numbered list.
