### ISSUE TITLE
Simple repetitions doesn't work

### ISSUE THREAD

**Issue by NicolasLethuillierPro** [carboneio/carbone#171]
Hi,

I try to use the repetition feature with quite simple objects, as follows:
JSON :
`{
  "buildings_number": 1,
  "building_names": [
    {
      "name": "BATIMENT A"
    }
  ],
}`

DOCX : 
![image](https://user-images.githubusercontent.com/107257068/201155543-3924a13d-041f-4b3f-9649-6054ffea673a.png)

PDF result : 
![image](https://user-images.githubusercontent.com/107257068/201155615-f4edff43-a663-48f5-b7b2-3b6ec5f04154.png)

I can't find out what I'm missing here...
I tried with a simple array of string, but it didn't work either, so I used objects with a "name" property to get closer to the documentation example.

I have no idea what I'm missing, can you see what I made wrong?

I was using the v2.0.0beta-3 but I tried with the final v2.0.0 and with the latest version, with the same result.

**Comment by steevepay** [comment]
Hello,
Can you share the template?

**Comment by NicolasLethuillierPro** [comment]
I just tried with the original odt file, and it worked. Then I tried again with the docx file... and it worked, with no modification in the file or in the code.
The only action I did since yesterday is rebooting my computer...
Sorry for the inconvenience, everything seems nice now :)
