### ISSUE TITLE
[Bug Report]: Error: Formatter "imageFit" does not exist. Do you mean "int"?

### ISSUE THREAD

**Issue by Fabri-Ferraro** [carboneio/carbone#177]
Carbone Version: 3.2.3
Node Version: 16.13.0
Browsers: Chrome
Desktop OS: Ubuntu 20.04
Other: docx

I'm trying to render a document with pictures, but when I try to compile, this problem happens.

https://i.imgur.com/d1FqxJV.png

I found a "solve" in Tutorials at this link: https://help.carbone.io/en-us/article/what-can-i-do-when-i-got-rendering-error-message-list-below-r1oznz/

But I'm already using version 3 of carbone, and 10 > of node.

And when I remove the function, the image doesn't appear, just the link that i'm passing in Alt.

So if i use carbone studio with the same template, works perfect.

**Comment by steevepay** [comment]
Hello

The `imageFit` formatter is not available on Carbone JS (free and open source version on github).
Dynamic images are only available on Carbone Enterprises products: Carbone Cloud (API or Studio) or Carbone On-premise.
