### ISSUE TITLE
Files templates manager using NestJs Api and Carbone

### ISSUE THREAD

**Issue by zaaack93** [carboneio/carbone#178]
Hello 

I make a new solution which makes a Backend API that's managed templates via API rest and save metadata of the templates in MongoDb 
Also, you can also generate based on templates saved on database with possible of adding data or options 
You can check my repository of my solution and contribute or fork this project

https://github.com/zaaack93/files-template-manager #

**Comment by steevepay** [comment]
Thank you for sharing the work!
