### ISSUE TITLE
[Bug Report]: Page Break is added in Repeat in ODT Templates

### ISSUE THREAD

**Issue by wodka** [carboneio/carbone#180]
**Environment**
Carbone Version: 3.5.5
Node Version: 18
Desktop OS: alpine linux

**Expected Behaviour**
I expect the group to repeat wit
hout a page break

**Actual Behaviour**
After every iteration a page break is added

**Steps to reproduce**
1. Open Studio
2. use the template: [transcript.odt](https://github.com/carboneio/carbone/files/11167295/transcript.odt)
3. use the following data:

```
{
  "paragraphs": [
    {
      "name": "First",
      "text": "OMG!"
    },
    {
      "name": "Second",
      "text": "OMG!"
    }
  ]
}
```

when using the same content in a docx template it is working! [transcript.docx](https://github.com/carboneio/carbone/files/11167379/transcript.docx)

**Screenshots**

![image](https://user-images.githubusercontent.com/385731/230300470-af64701a-f638-4dd5-8577-1e2c36edf202.png)

vs using the same content but inside a docx file:
![image](https://user-images.githubusercontent.com/385731/230302143-e3423211-80e6-4526-b5ea-16f9890307a2.png)

**Comment by JujuEasilys** [comment]
Hello @wodka , I don't think it's a bug.
Your 2 template are different, the odt one is set up to generate a page brake for each loop and not the docx one.

I have change for your 2 template, now the break page is generate on the docx (not tested but it should be).

You will find the set up here

https://help.carbone.io/en-us/article/how-to-insert-a-page-break-without-having-a-blank-page-at-the-end-of-the-report-j6jy00/

[transcript.docx](https://github.com/carboneio/carbone/files/12304032/transcript.docx)
[transcript.odt](https://github.com/carboneio/carbone/files/12304035/transcript.odt)

**Comment by wodka** [comment]
Hi @JujuEasilys - how is the ODT set up to generate a page break? All the parts of the loop are just using line breaks.

-> I think the bug is that there are page breaks, even though non are defined

**Comment by JujuEasilys** [comment]
Hello

The odt I put in my comment shoud not generate page break, but now the docx I put should do it

**Comment by JujuEasilys** [comment]
The odt you put where set up to generate page break without blank page at the end (that the link I put to know how to set up)

**Comment by wodka** [comment]
ah - now I got it - I was really just looking for page breaks, thank you! and yes, now I no longer think it is a bug!
