### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by devinleighsmith** [carboneio/carbone#183]
**Environment**
Carbone Version: [e.g. Carbone 4.x.x]
Node Version: n/a (carbone studio)
Browsers: [e.g. firefox 112.0.2]
Desktop OS: [windows]

**Expected Behaviour**
Carbone should render the owners {d.file.owners[i].owner_string} within the expected table cell

**Actual Behaviour**
Carbone renders the owners after the table, not within the table at all.

**Steps to reproduce**
Steps to reproduce the bug:
1. Go to carbone studio
2. copy the json in this bug report. upload the document in this bug report
3. See error
4. Get a warning about a corrupt document when downloading/opening

**Screenshots**
![image](https://user-images.githubusercontent.com/41091511/235273345-61ee9f31-fb11-472c-ac7d-421ee0f54230.png)

![image](https://user-images.githubusercontent.com/41091511/235273573-5992e0e2-bbc4-4005-bf44-9d5b0ad8010f.png)

**Reproduction Link / Code example**
JSON:
```
{
  "file": {
    "properties": [
      {
        "pid": "005-127-343",
        "legal_description": "LOT 53, SECTIONS 26 AND 27, VICTORIA DISTRICT, PLAN 11000",
        "region": "South Coast Region",
        "address": {
          "line_1": "100 - 1223 Admirals rd",
          "line_2": "",
          "line_3": "",
          "city": "VICTORIA",
          "province": "",
          "postal": "V9A 0H2",
          "country": "",
          "address_string": "100 - 1223 Admirals rd\nVICTORIA\nV9A 0H2"
        },
        "location_of_land": "",
        "district": "Vancouver Island District"
      },
      {
        "pid": "003-159-701",
        "legal_description": "LOT 17, SECTION 8A, VICTORIA DISTRICT, PLAN 8958",
        "region": "South Coast Region",
        "address": {
          "line_1": "100 - 1223 Admirals rd",
          "line_2": "",
          "line_3": "",
          "city": "VICTORIA",
          "province": "",
          "postal": "V9A 0H2",
          "country": "",
          "address_string": "100 - 1223 Admirals rd\nVICTORIA\nV9A 0H2"
        },
        "location_of_land": "",
        "district": "Vancouver Island District"
      }
    ],
    "owners": [
      {
        "given_name": "an owner",
        "last_name_or_corp_name": "blah",
        "other_name": "",
        "incorporation_number": "",
        "registration_number": "",
        "address": {
          "line_1": "1",
          "line_2": "2",
          "line_3": "3",
          "city": "",
          "province": "",
          "postal": "v9a1s1",
          "country": "Canada",
          "address_string": "1\n2\n3\nv9a1s1\nCanada"
        },
        "is_corporation": false,
        "owner_string": "an owner blah",
        "email": "test@test.ca",
        "is_primary_contact": true
      }
    ],
}
```
template:
[reproduce_error.docx](https://github.com/carboneio/carbone/files/11358004/reproduce_error.docx)

carbone template: 
![image](https://user-images.githubusercontent.com/41091511/235273489-769bceba-8e89-482a-a338-e5e3caf9098d.png)

**Other comments**
May be related to the depth of the object being traversed, the following template works as expected:

![image](https://user-images.githubusercontent.com/41091511/235273707-0fff44ad-0b18-410a-8ed3-d11816b13203.png)

**Comment by steevepay** [comment]
Hello, it is not possible to mix printing two different loops, I would recommend you change the design of your JSON data-set by moving the list "owners" into the "properties" list, such as:
```json
{
  "file": {
    "properties": [
      {
        "pid": 1,
        "owners": [
          {
            "owner_string": "value 1"
          },
          {
            "owner_string": "value 2"
          }
        ]
      },
      {
        "pid": 2,
        "owners": [
          {
            "owner_string": "value 3"
          },
          {
            "owner_string": "value 3"
          }
        ]
      }
    ]
  }
}
```
Then you can access values with the following Carbone tags:
```
{d.file.properties[i]}
{d.file.properties[i].pid}
{d.file.properties[i].owners[i].owner_string}
{d.file.properties[i].owners[i+1].owner_string}
{d.file.properties[i+1]}
```
Let me know if it is good on your side.
