### ISSUE TITLE
[Bug Report]: ucFirst doesn't work when all UPPERCASE

### ISSUE THREAD

**Issue by danibs** [carboneio/carbone#184]
**Environment**
Carbone Version: https://studio.carbone.io/#/studio  (4.x.x)
Browsers: Chromium Version 114.0.5735.106
Desktop OS: Ubuntu 20.04
Other: LibreOffice: 7.5.4.2

**Expected Behaviour**
First letter must be **uppercase**

JSON:
{
  "name": "NAME",
  "surname": "surname"
}

Template document:
{d.name:ucFirst()} {d.surname:ucFirst()}

**Result**

![immagine](https://github.com/carboneio/carbone/assets/30932554/057e875f-9a0c-4450-86eb-80798c731402)

**Comment by JujuEasilys** [comment]
Hello 
Your NAME has allready ucFirst
If you want ucFirst and the other letter on minuscule, you have to convert all the string on lower Case you can do:

{d.name:lowerCase( ):ucFirst()} {d.surname:ucFirst()} 

You should attempt your goal

**Comment by steevepay** [comment]
Hi,

As mentioned in the documentation: `it uppercases the first letter`, that's it.
Source: https://carbone.io/documentation.html#ucfirst-

Then, if you want to lowercase the word, you can follow the @JujuEasilys solution ;)

**Comment by danibs** [comment]
> Hi,
> 
> As mentioned in the documentation: `it uppercases the first letter`, that's it. Source: https://carbone.io/documentation.html#ucfirst-
> 
> Then, if you want to lowercase the word, you can follow the @JujuEasilys solution ;)


That is ok.
But please update documentation, as I showed it is not correct ;-)
