### ISSUE TITLE
[Bug Report]: Typo in documentation

### ISSUE THREAD

**Issue by danibs** [carboneio/carbone#185]
1)
Section: https://carbone.io/documentation.html#drop-element-

"meaning the actual **an** 2 following paragraph will be deleted."

I think you want to write "and".

2)
Conditionally displaying a data based on a test expression, such as {d.value:ifEQ(true):**print**('The value is true!')}

I think you want to write "show".

**Comment by steevepay** [comment]
Thank you! Fixed!
