### ISSUE TITLE
[Feature Request]: nested alias

### ISSUE THREAD

**Issue by danibs** [carboneio/carbone#187]
Hi
Suppose to have:
```json
{
	"f1": "1",
	"fcomposite": {
		"c1": "c",
		"d1": "d",
		"ffcomposite": {
			"e1": "e"
		}
	}
}
```

The way to define aliases are:

`{#myalias = d.f1}`
`{#composite1 = d.f1.fcomposite}`
`{#composite2 = d.f1.fcomposite.ffcomposite}`

It could be useful to define alias using another alias:
`{#myalias = d.f1}`
`{#composite1 = $myalias.fcomposite}`
`{#composite2 = $composite1.ffcomposite}`

What do you think about?

**Comment by steevepay** [comment]
Nested aliases is planned on our roadmap, it will probably come in the next major version of Carbone: v5.0.0.
