### ISSUE TITLE
[Feature Request]: arrayMap with line-break

### ISSUE THREAD

**Issue by danibs** [carboneio/carbone#188]
Permit to arrayMap to separate elements using line-break.

It is simpler to have:
`[{'id':2,'name':'homer'},{'id':3,'name':'bart'}]:arrayMap('\n')`

instead of using:
```
{d.name[i]}
{d.name[i+1]}
```

**Comment by steevepay** [comment]
For now, it is not possible to render line break characters inserted with arrayMap.
On the latest version of Carbone Cloud (Enterprise), the following syntax does work:
```
{d.list:arrayMap('<br>', '', 'name'):html}
```
The `<br>` break line HTML tag is inserted, then rendered with the `:html` formatter (see screenshot).
<img width="1504" alt="Screenshot 2023-08-14 at 13 25 21" src="https://github.com/carboneio/carbone/assets/16964532/4a66eb82-9fb0-4566-867d-e2364498a8c2">

In future version of Carbone, we will probably support this kind of syntax:
```
{d.list:arrayMap('\n', '', 'name'):convCRLF}
```

**Comment by maxdelorme** [comment]
Hi, 

When I test `{d.list:arrayMap('<br>', '', 'name'):html} ` 
I can't make it work. On which version are you ?

**Comment by steevepay** [comment]
It is working only with Carbone Enterprise, either with our Carbone Cloud API or Studio (https://studio.carbone.io/)

the `:html` formatter is not included into Carbone JS (the current open source repository, community version).
