### ISSUE TITLE
[Bug Report]: ifEQ:showBegin doesn't work under some conditions

### ISSUE THREAD

**Issue by danibs** [carboneio/carbone#190]
**Environment**
Carbone Version: Carbone Studio using v.4.x
Browsers: Chromium v.114.0.5735.106
Desktop OS: Ubuntu 20.04
Other: LibreOffice 7.5.4.2

**Expected Behaviour**
Show text when ifEQ returns true

**Actual Behaviour**
Without space between showEnd and showBegin, it doesn't correct print text when ifEQ is matched.

**Steps to reproduce**
Data is:
```json
{
  "v": "A"
}
```

Here you can see a space between showEnd and showBegin:
![immagine](https://github.com/carboneio/carbone/assets/30932554/1514ecfe-0770-42a6-9f46-1d479e9ce484)

The result when **v=A**:
![immagine](https://github.com/carboneio/carbone/assets/30932554/bc7d2e21-98d9-4bab-bbc6-e5577ef7ab1f)

The result when **v=B**:
![immagine](https://github.com/carboneio/carbone/assets/30932554/63f5c838-3cb4-4cf1-9e16-91349112b84f)

Without a space between showEnd and showBegin:
![immagine](https://github.com/carboneio/carbone/assets/30932554/7658b744-81d6-46b8-beeb-3ab9475295fa)

The result when **v=A** (both):
![immagine](https://github.com/carboneio/carbone/assets/30932554/e8b327ba-d66f-4d74-b579-d7857f41d43f)

The result when **v=B** (blank):
![immagine](https://github.com/carboneio/carbone/assets/30932554/a7cf8e55-18bc-436c-b2e5-ebedc0b1dddf)

**Comment by steevepay** [comment]
Hello,

Thank you for reaching us, we are aware of issues about `showBegin/showEnd` not working in specific cases, particularly when there is not clear separators between `showEnd` and `showBegin`.

I would recommend you:
- Inserting a space or newline between the end and beginning of a new condition `showBegin/showEnd`
- Using the `:show` and `:elseShow` formatter if you only want to print a text, such as `{d.v:ifEQ(A):show('AAAAA'):elseShow('BBBBB')}`. 
- If you are using Carbone Enterprise version (Cloud or On-premise) you can use the drop formatter: https://carbone.io/documentation.html#drop-element-

Let me know if it is good on your side.

**Comment by danibs** [comment]
That is good, I already adopted solutions you suggests.
That was just a bug for you, but you are already aware so... that ok.
Thank you!
