### ISSUE TITLE
License confirmation

### ISSUE THREAD

**Issue by cold01water** [carboneio/carbone#192]
I would like to know when using CarboneJS to develop a program might constitute a license violation. 
Could the following scenarios be considered license violations?

1. Incorporating CarboneJS into an estimation tool to enable the creation of calc documents.
2. Developing the aforementioned tool under a contract or selling it to another company.
3. Creating a tool that uses CarboneJS to generate documents via an HTTP API.
4. Integrating the aforementioned tool with low-code software and deploying it in a customer-facing system.

Of course, I will clearly indicate the use of CarboneJS, and if necessary, I am open to releasing it as open-source software (OSS).

**Comment by steevepay** [comment]
As long as your scenarios are not offering Carbone Community Edition Software as a hosted Document-Generator-as-a-Service like [Carbone Cloud](https://carbone.io/pricing.html), you can use all Community features for free.

> Creating a tool that uses CarboneJS to generate documents via an HTTP API.
Until the API is only consumed by your estimation tool, that's good.
If you monetize the API and create a competing service of Carbone Cloud / Carbone On-premise, that's a violation.
