### ISSUE TITLE
Can I Repeat Entire Pages?

### ISSUE THREAD

**Issue by ConProgramming** [carboneio/carbone#214]
Love carbone. We're paying for it through AWS Marketplace.

Is there a way to repeat entire pages? The looping of a table works great, but I have entire pages with graphics and their own data. Being able to repeat entire pages would be very useful.

Best idea right now is to make each page it's own carbone report, but that's more expensive (multiple calls), and requires writing something to connect them back together.

**Comment by steevepay** [comment]
Hello @ConProgramming, can you reach us on the Carbone live chat with a template, JSON data-set and the result your expect ? thank you

**Comment by ConProgramming** [comment]
Live chat was super helpful, thanks!
