### ISSUE TITLE
[Bug Report]: No file send

### ISSUE THREAD

**Issue by chdonncha** [carboneio/carbone#216]
When creating a new template on https://studio.carbone.io/#/studio using a free account I receive the following error:

![image](https://github.com/user-attachments/assets/b05defe4-7fc2-403c-8b6c-d87d08e52f9e)

Also is the error message meant to be "No file sent?" may be a minor grammar error

**Comment by steevepay** [comment]
Can you please contact the Carbone support with the template file you tested ? 
You can send to support@carbone.io

**Comment by chdonncha** [comment]
Provided details on customer support but issue seemed related to browser:

On MacOS using MS Edge the finder WOULD NOT open after clicking the Attachment Input any number of times

On MacOS using Google Chrome the finder WOULD open after clicking the Attachment Input on first click
