### ISSUE TITLE
bindColor cell example

### ISSUE THREAD

**Issue by albertotruccolo** [carboneio/carbone#51]
good morning,
I have a question, the bindcolor on an excel template does not work, can I have working examples?

{d.to_pay} -> color cell 0000ff

i write {bindColor(0000ff, hexa) = d.color3} in another cell and my data json is:

data.total_pay = 5
data.color = '#FF0000';
data.color2 = '#00FF00';
data.color3 = '#0000FF';
data.color4 = 'red';

can you help me?

**Comment by steevepay** [comment]
Hi @albertotruccolo,

Thanks for your question, your example is fine.
We have discovered an issue with the `{bindColor()}` marker.
For now, you can manage dynamic colors on ODT files. 
We'll coming back to you and we will fix this issue maybe on the next release.
If you can't wait, feel free to fork the project and contribute :)

**Comment by steevepay** [comment]
Quick update: the bindColor formatter can't work on a XLSX template until we rewrite the XLSX rendering.
Use only ODS templates for now.
