### ISSUE TITLE
[Feature Request]: Add support for hyperlinks

### ISSUE THREAD

**Issue by genadis** [carboneio/carbone#53]
**Problem to solve**
Currently there seems to be no way to add hyperlinks
(http://officeopenxml.com/WPhyperlink.php)

**Proposed solution**
Add option to write to `document.xml.rels` via formatter context. So we would be able to implement hyperlinks.

**Describe alternatives you've considered**
I've considered implementing via formatter similar to `convCRLF()`. But hyperlinks require writing `Relationship` to `document.xml.rels`.

**Comment by NestorPerez13** [comment]
I have the same problem, i need to add an hyperlink to an excel sheet, firstly it appear like this:
![image](https://user-images.githubusercontent.com/36772328/71915432-5bbd7680-3141-11ea-9ed3-9ea35e0734cb.png)

As soon as i click ok, excel escapes the URL and it appear like this:
![image](https://user-images.githubusercontent.com/36772328/71915488-798adb80-3141-11ea-97e5-b2d7da485287.png)

Carbone is unable to parse that "hyperlink", however the visible text in the cell is correct, if someone knows a workaround to solve this i would appreciate.

**Comment by steevepay** [comment]
@NestorPerez13 It is not possible yet to apply hyperlinks to an XLSX/ODS template.
We are investigating the proposed solution from @genadis.
Hold on, we will come back to you.

**Comment by steevepay** [comment]
To let you know, the next version of Carbone will support hyperlinks with ODS and ODT files.
At this moment, there is some limitations with DOCX and XLSX.

**Comment by genadis** [comment]
@steevepay great news!
Are there plans for DOCX and XLSX? or add option to write to `document.xml.rels` via formatter context?

Thanks!

**Comment by steevepay** [comment]
Carbone is writing to the file `document.xml.rels` but the feature needs to be improved to support lists of hyperlinks for DOCX and XLSX (for example the screenshot of @NestorPerez13).

**Comment by steevepay** [comment]
Dynamic hyperlinks are available since the v3.0.0 for Carbone Enterprise Edition, here is the documentation:
https://carbone.io/documentation.html#dynamic-hyperlinks

**Comment by rriemann** [comment]
I thought of using Carbone to generate GDPR audit reports. So can you confirm that I cannot use Carbone free software to place a clickable URL from JSON in an odt file?

Our reports are sensitive, so that using free software on premise is a big plus.
